#     _____ _            ___  _ _
#    |  __ (_)          / _ \| | |
#    | |  \/___   _____/ /_\ \ | |   Made by:
#    | | __| \ \ / / _ \  _  | | |   BlitzGamer_88
#    | |_\ \ |\ V /  __/ | | | | |
#     \____/_| \_/ \___\_| |_/_|_|

# If you enable this, items will be given to the player that uses the /giveall command as well.
give-rewards-to-sender: false
# If you enable this, only players with the permission 'giveall.receive' will be able to get the rewards.
requires-permission: false

# If enabled, this plugin will hook into vault and you will be able to use the economy feature of the plugin.
# If you edited this option, you'll have to restart the server for it to take effect.
hooks:
  vault: true